############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "About"
#url = "/about"
#weight = 2

#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 3

[[main]]
name = "Racing"
url = "/class"
weight = 3

[[main]]
name = "Our Track"
url = "/track"
weight = 4

[[main]]
name = "Gallery"
url = "/media"
weight = 5


#[[main]]
#name = "Example formats"
#url = "/elements"
#weight = 6

#[[main]]
#weight = 6
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"


# footer menu
#[[footer]]
#name = "About"
#url = "/about"
#weight = 1

